import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header/Header";
import { Roboto } from "next/font/google"
import Footer from "@/components/Footer/Footer";


const roboto = Roboto({
  subsets:["latin"],
  weight: ["400","700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Header></Header>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
